
@token = xxxxxx

### Recuperar ruta de la API
GET http://localhost:3000/
### Recuperar todas las películas
GET http://localhost:3000/users
Authorization: Bearer {{token}}


### Recuperar una película por id
GET http://localhost:3000/users/458a0de3-c054-40c4-8f64-c7bc01b022b2
Authorization: Bearer {{token}}

### Recuperar todas las películas por un género
GET http://localhost:3000/users?genre=sci-fi

### Crear una película con POST
POST http://localhost:3000/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "marcela.estrada@ricaurteruedaabogados.com",
  "password": "DiccionarioMarcelaE*123",
  "name": "Marcela E.",
  "role": "Editor"
}

### Recuperar todas las películas
GET http://localhost:3000/users
Authorization: Bearer {{token}}

### Borrar una película
DELETE http://localhost:3000/users/654aa161aad9f770da0ab269

### Actualizar una película
PATCH http://localhost:3000/users/458a0de3-c054-40c4-8f64-c7bc01b022b2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "RENOMBRADOO"
}