
### Recuperar ruta de la API
GET http://localhost:3000/
### Recuperar todas las películas
GET http://localhost:3000/users

### Recuperar todas las películas por título
GET http://localhost:3000/movies

### Recuperar una película por id
GET http://localhost:3000/users/2

### Recuperar todas las películas por un género
GET http://localhost:3000/users?role=admin

### Crear una película con POST
POST http://localhost:3000/users
Content-Type: application/json

{
	"sql": "SELECT * FROM users",
	"email": "LINODE@asdasd.com",
	"password": "fefefefefa",
	"name": "Danna Mendez",
	"role": "user",
	"avatar": "https://img.fruugo.com/product/4/49/14441494_max.jpg"
}

### Recuperar todas las películas
GET http://localhost:3000/users

### Borrar una película
DELETE http://localhost:3000/users/78492341-3a69-4c42-b180-95d3bab47a7e

### Actualizar una película
PATCH http://localhost:3000/users/4
Content-Type: application/json

{
  "name": "1942"
}